---
openapi: 3.0.0
info:
  title: A Collection of Playbooks to trigger response actions.
  description: A collection of API Calls to trigger Playbooks for response actions such as blocking IP's, or isolating hosts in MDE.
  version: v1
servers:
  - url: https://prod-23.canadacentral.logic.azure.com:443/workflows/1e5b8c3018634a9494c749a61a196713/triggers/manual/paths/invoke
paths:
  /:
    post:
      operationId: blockIP
      description: Trigger a Playbook to block a specific IP Address across all Defender for Endpoint hosts by adding a new Block IOC to the indicators list.
      parameters:
        - in: query
          name: api-version
          schema:
            type: string
            default: 2016-10-01
          description: API Version, always use the value 2016-10-01
        - in: query
          name: sp
          schema:
            type: string
            default: /triggers/manual/run
          description: Trigger to run, always use the default value /triggers/manual/run
        - in: query
          name: sv
          schema:
            type: string
            default: 1.0
          description: SV Version, always use the default value 1.0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                        functionName:
                          type: string
                          description: Name of the Playbook to trigger, always use value blockIP
                          default: blockIP
                        caller:
                          type: string
                          description: E-mail address of the analyst triggering the Playbook always use value officechris@stelznet.com
                          default: officechris@stelznet.com
                        question:
                          type: string
                          required: true
                          description: The entire prompt used to trigger this Playbook
                          example: Can you block the IP Address 176.45.34.12?
                        ipAddress:
                          type: string
                          required: true
                          description: The specific IP Address to block
      responses:
        "200":
          description: Playbook Executed
          content:
            application/json:
              schema:
                type: object
  /:
    post:
      operationId: isolateMDEDevice
      description: Trigger a Playbook to block to isolate a specific machine using Defender for Endpoint
      parameters:
        - in: query
          name: api-version
          schema:
            type: string
            default: 2016-10-01
          description: API Version, always use the value 2016-10-01
        - in: query
          name: sp
          schema:
            type: string
            default: /triggers/manual/run
          description: Trigger to run, always use the default value /triggers/manual/run
        - in: query
          name: sv
          schema:
            type: string
            default: 1.0
          description: SV Version, always use the default value 1.0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                        functionName:
                          type: string
                          description: Name of the Playbook to trigger, always use value isolateMDEDevice
                          default: isolateMDEDevice
                        caller:
                          type: string
                          description: E-mail address of the analyst triggering the Playbook always use value officechris@stelznet.com
                          default: officechris@stelznet.com
                        question:
                          type: string
                          required: true
                          description: The entire prompt used to trigger this Playbook
                          example: Can you isolate the machine STELZNET-UTIL?
                        hostName:
                          type: string
                          required: true
                          description: The specific host to block
      responses:
        "200":
          description: Playbook Executed
          content:
            application/json:
              schema:
                type: object
                
