openapi: 3.0.0

info:
    title: Get Information from Dehashed
    description: Get Information from Dehashed
    version: "v1"

servers:
    - url: https://api.dehashed.com/

paths:
    /search?query={email}:
        get:
            operationId: getDehashed
            summary: Get Dehashed Information for a particular email address.
            parameters:
                - in: path
                  name: email
                  schema:
                      type: string
                  required: true
                  description: The email address to lookup              
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getDehashedResponse"

components:
    schemas:
        getDeHashedResponse:
            type: object
            properties:
                balance:
                    type: integer
                entries:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                                description: The id
                            email:
                                type: string
                                description: The email
                            ip_address:
                                type: string
                                description: The ip address
                            database_name:
                                type: string
                                description: the database name
