---
openapi: 3.0.0
info:
  title: Create a new incident through a POST request to the Pager Duty API with a specific title.
  description: Generate a JSON Payload for a POST request to the Pager Duty API which will have a new incident created with a specific title.
  version: v1
servers:
  - url: https://api.pagerduty.com
paths:
  /incidents:
    post:
      operationId: createIncident
      description: Create an incident in pager duty with a specific title
      summary: Create an incident in pager duty with a specific title
      parameters:
        - in: header
          name: From
          schema:
            type: string
          required: true
          description: From e-mail address will always be officechris@gmail.com
          default: officechris@gmail.com
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                incident:
                  type: object
                  required: true
                  properties:
                    type:
                      type: string
                      required: true
                      default: incident
                    title:
                      type: string
                      description: The specific title or summary of the incident
                      required: true
                      example: Investigation of Windows Print Spooler Remote Code Execution Vulnerability (CVE-2021-34527)
                    service:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The incident service id is always PP2PR00
                          required: true
                          default: PP2PR00
                        type:
                          type: string
                          required: true
                          description: The incident type is always service_reference
                          default: service_reference
      responses:
        "201":
          description: The incident object created.
          content:
            application/json:
              schema:
                type: object
