---
openapi: 3.0.0
info:
  title: Create Pager Duty Incident
  description: Create Pager Duty Incident
  version: v1
servers:
  - url: https://api.pagerduty.com
paths:
  /incidents:
    post:
      operationId: createIncident
      description: Create an incident synchronously without a corresponding event from
        a monitoring service.
      summary: Create an Incident
      parameters: null
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                incident:
                  type: object
                  description: Details of the incident to be created.
                  required: true
                  properties:
                    type:
                      type: string
                      required: true
                      enum:
                        - incident
                    title:
                      type: string
                      description: A succinct description of the nature, symptoms, cause, or effect of
                        the incident.
                      required: true
                    service:
                      type: object
                      properties:
                        id:
                          type: string
                          required: true
                          enum:
                            - PP2PR00
                        type:
                          type: string
                          required: true
                          enum:
                            - service_reference
      responses:
        "201":
          description: The incident object created.
          content:
            application/json:
              schema:
                type: object
