openapi: 3.0.0

info:
    title: Create Pager Duty Incident
    description: Create Pager Duty Incident
    version: "v1"

servers:
    - url: https://api.pagerduty.com

paths:
    /incidents:
        post:
          x-pd-requires-scope: incidents.write
          x-pd-operation-limit: true
          tags:
          - Incidents
          operationId: createIncident
          description: Create an incident synchronously without a corresponding event from a monitoring service.
          summary: Create an Incident
          parameters:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    incident:
                      type: object
                      description: Details of the incident to be created.
                      properties:
                        type:
                          type: string
                          enum:
                          - incident
                        title:
                          type: string
                          description: A succinct description of the nature, symptoms, cause,
                            or effect of the incident.
                        urgency:
                          type: string
                          description: The urgency of the incident
                          enum:
                          - high
                          - low
                        body:
                          "$ref": "#/components/schemas/IncidentBody"
                        incident_key:
                          type: string
                          description: A string which identifies the incident. Sending subsequent
                            requests referencing the same service and with the same incident_key
                            will result in those requests being rejected if an open incident
                            matches that incident_key.
                      required:
                      - type
                      - title
                      - service
                  required:
                  - incident
          components:
            schemas:
                IncidentBody:
                  type: object
                  properties:
                    details:
                      type: object
                      description: Additional incident details.
                  required:
                  - type
          responses:
            '201':
              description: The incident object created.
              content:
                application/json:
                  schema:
                    type: object
