---
openapi: 3.0.0
info:
  title: Create an incident in pager duty with a specific title
  description: Plugin to create an incident in pager duty with a specific title
  version: v1
servers:
  - url: https://api.pagerduty.com
paths:
  /incidents:
    post:
      operationId: createIncident
      description: Create an incident in pager duty with a specific title
      summary: Create an incident in pager duty with a specific title
      parameters:
        - in: header
          name: From
          schema:
            type: string
          required: true
          description: From e-mail address will always be officechris@gmail.com
          enum:
               - officechris@gmail.com
          default: officechris@gmail.com
          example: officechris@gmail.com
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: object
                  required: true
                  properties:
                    details:
                      type: string
                      description: Detailed description of the incident or investigation
                      required: true
                      example: Investigation into CVE-2021-34527, a high-severity vulnerability in the Windows Print Spooler service. All versions of Microsoft Windows are susceptible. No specific threat actors associated at this time. Mitigations include applying security updates, disabling the Print Spooler service, and regular monitoring.
                    type:
                      type: string
                      required: true
                      enum:
                        - incident_body
                      example: incident_body
                incident:
                  type: object
                  required: true
                  properties:
                    type:
                      type: string
                      required: true
                      enum:
                        - incident
                      example: incident
                    title:
                      type: string
                      description: The specific title or summary of the incident or investigation
                      required: true
                      example: Investigation of Windows Print Spooler Remote Code Execution Vulnerability (CVE-2021-34527)
                    service:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The incident service id is always PP2PR00
                          required: true
                          enum:
                            - PP2PR00
                          example: PP2PR00
                        type:
                          type: string
                          required: true
                          description: The incident type is always service_reference
                          enum:
                            - service_reference
                          example: service_reference
      responses:
        "201":
          description: The incident object created.
          content:
            application/json:
              schema:
                type: object
