openapi: 3.0.0

info:
    title: Get Virus Total IP Information
    description: Get Information about an IP from Virus Total
    version: "v1"

servers:
    - url: https://www.virustotal.com/api/v3/ip_addresses/

paths:
    /v3/ip_addresses/{ip}:
        get:
            operationId: getVirusTotalIP
            summary: Get Virus Total IP Information for a particular IP address.
            parameters:
                - in: path
                  name: ip
                  schema:
                      type: string
                  required: true
                  description: The ip address to lookup              
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getVTIPResponse"

components:
    schemas:
        getVTIPResponse:
            type: object
            properties:
                attributes:
                    type: object
                    properties:
                        jarm:
                            type: string